id: P002997
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W30280
  title: བོད་ཀྱི་རྟའི་གསོ་དཔྱད་གཞུང་ལུགས་བདམས་བསྒྲིགས
  author: ''
  volumes:
    15a63bee8cee443184fcae9f5a466ee9:
      image_group_id: I1GS55126
      title: ''
      volume_number: 1
      total_pages: 205
      base_file: v001.txt
