id: P002997
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:33:23.749024
source_metadata:
  id: bdr:W30280
  title: བོད་ཀྱི་རྟའི་གསོ་དཔྱད་གཞུང་ལུགས་བདམས་བསྒྲིགས
  author: ''
  volumes:
    15a63bee8cee443184fcae9f5a466ee9:
      image_group_id: I1GS55126
      title: ''
      volume_number: 1
      total_pages: 205
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
